### ISSUE TITLE
안드로이드에서 스크롤뷰안에 작은 맵을 클릭하면 튕김

### ISSUE THREAD

**Issue by minemos** [QuadFlask/react-native-naver-map#102]
### Version of react-native-naver-map libraries

0.0.66 버전 사용중입니다.

### Version of react-native

"react-native": "0.64.0"

사용중입니다

### Platforms you faced the error (IOS or Android or both?)

안드로이드 실 기기에서 튕깁니다

### Expected behavior

터치하면 지도가 움직여야 하는데, 안드로이드에서만 튕겨버립니다.
이외에 화면을 다 덮는 지도는 멀쩡한데 이상하게 저 화면만 튕깁니다.

### Actual behavior

![KakaoTalk_Photo_2021-06-07-18-06-17](https://user-images.githubusercontent.com/24834933/120990017-19c3b480-c7bb-11eb-864e-07b8d3d2b1a7.jpeg)

ScrollView 안에 있는 뷰입니다.
```js
<NaverMapView
            ref={Map}
            style={{ height: 155 }}
            zoomControl={false}
            showsMyLocationButton={false}
            center={{ latitude: 37, longitude: 127, zoom: 17 }}
            useTextureView
            scrollGesturesEnabled
            zoomGesturesEnabled
            tiltGesturesEnabled
            rotateGesturesEnabled
            stopGesturesEnabled>
            <Marker
              coordinate={{
                latitude: Number(data.Latitude),
                longitude: Number(data.Longitude),
              }}
              flat={true}
              caption={{
                text: data.Name,
                textSize: 14,
                color: colors.primary,
                haloColor: colors.white,
              }}
            />
          </NaverMapView>
```

### Tested environment (Emulator? Real Device?)

안드로이드 실 기기 입니다.

### Android Log

java.lang.IllegalArgumentException: Unable to find JSIModule for class UIManager
        at com.facebook.react.bridge.JSIModuleRegistry.getModule(JSIModuleRegistry.java:24)
        at com.facebook.react.bridge.CatalystInstanceImpl.getJSIModule(CatalystInstanceImpl.java:564)
        at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:90)
        at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:46)
        at com.facebook.react.uimanager.UIManagerHelper.getUIManagerForReactTag(UIManagerHelper.java:40)
        at com.facebook.react.animated.NativeAnimatedNodesManager.handleEvent(NativeAnimatedNodesManager.java:505)
        at com.facebook.react.animated.NativeAnimatedNodesManager.onEventDispatch(NativeAnimatedNodesManager.java:483)
        at com.facebook.react.uimanager.events.EventDispatcherImpl.dispatchEvent(EventDispatcherImpl.java:116)
        at com.facebook.react.uimanager.JSTouchDispatcher.handleTouchEvent(JSTouchDispatcher.java:74)
        at com.facebook.react.ReactRootView.dispatchJSTouchEvent(ReactRootView.java:283)
        at com.facebook.react.ReactRootView.onInterceptTouchEvent(ReactRootView.java:201)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3454)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:913)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1957)
        at android.app.Activity.dispatchTouchEvent(Activity.java:4182)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:871)
        at android.view.View.dispatchPointerEvent(View.java:15458)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7457)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7233)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6595)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6786)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6843)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9880)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9718)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9671)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10014)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:206)

**Comment by QuadFlask** [comment]
#97 이슈와 동일한것 같습니다. 0.64.2 에서 업데이트되었다고 하니 올려보시고 테스트해주세요.

**Comment by minemos** [comment]
> #97 이슈와 동일한것 같습니다. 0.64.2 에서 업데이트되었다고 하니 올려보시고 테스트해주세요.

해결되었습니다!
