### ISSUE TITLE
지도내 터치시 안드로이드 adb 에러 로그 

### ISSUE THREAD

**Issue by star4680** [QuadFlask/react-native-naver-map#125]
### Version of react-native-naver-map libraries

0.0.66

### Version of react-native

0.65

### Platforms you faced the error (IOS or Android or both?)

Android 

### Expected behavior

에러로그 발생하지 않음

### Actual behavior

지도내 터치시 번들에서 에러는 발생하지 않지만 android logcat 에서 아래와 같은 에러가 발생합니다. 
reanimated, gesture handler 라이브러리 버전도 변경해봤지만 여전히 발생하고 있는데 도저히 원인이 뭔지 모르겠습니다.
또한 안드로이드, iOS 공통적으로 일정시간 동안 지도를 터치하거나 이동시 메모리가 환원되지 않고 memory leak 발생하여 앱 crash 발생하는 현상도 보이는데 아래 이슈와 관련된걸까요. 

확인 좀 부탁드려요. 감사합니다.

com.facebook.react.bridge.ReactNoCrashSoftException: Cannot find EventEmitter for receivedTouches: ReactTag[2131296476] UIManagerType[2] EventName[topTouchEnd]
12-20 08:52:07.599 25481 29106 E unknown:ReactEventEmitter:     at com.facebook.react.uimanager.events.ReactEventEmitter.receiveTouches(ReactEventEmitter.java:74)
12-20 08:52:07.599 25481 29106 E unknown:ReactEventEmitter:     at com.facebook.react.uimanager.events.TouchesHelper.sendTouchEvent(TouchesHelper.java:106)
12-20 08:52:07.599 25481 29106 E unknown:ReactEventEmitter:     at com.facebook.react.uimanager.events.TouchEvent.dispatch(TouchEvent.java:166)
12-20 08:52:07.599 25481 29106 E unknown:ReactEventEmitter:     at com.facebook.react.uimanager.events.TouchEvent.dispatchModern(TouchEvent.java:176)
12-20 08:52:07.599 25481 29106 E unknown:ReactEventEmitter:     at com.facebook.react.uimanager.events.EventDispatcherImpl$DispatchEventsRunnable.run(EventDispatcherImpl.java:369)
12-20 08:52:07.599 25481 29106 E unknown:ReactEventEmitter:     at android.os.Handler.handleCallback(Handler.java:883)
12-20 08:52:07.599 25481 29106 E unknown:ReactEventEmitter:     at android.os.Handler.dispatchMessage(Handler.java:100)
12-20 08:52:07.599 25481 29106 E unknown:ReactEventEmitter:     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
12-20 08:52:07.599 25481 29106 E unknown:ReactEventEmitter:     at android.os.Looper.loop(Looper.java:237)
12-20 08:52:07.599 25481 29106 E unknown:ReactEventEmitter:     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
12-20 08:52:07.599 25481 29106 E unknown:ReactEventEmitter:     at java.lang.Thread.run(Thread.java:919)
12-20 08:52:07.748   782   855 E Netd    : getNetworkForDns: getNetId from enterpriseCtrl is netid 0

### Tested environment (Emulator? Real Device?)

안드로이드 실기기 공통적으로 발생.

**Comment by scy0334** [comment]
> ### Version of react-native-naver-map libraries
> 0.0.66
> 
> ### Version of react-native
> 0.65
> 
> ### Platforms you faced the error (IOS or Android or both?)
> Android
> 
> ### Expected behavior
> 에러로그 발생하지 않음
> 
> ### Actual behavior
> 지도내 터치시 번들에서 에러는 발생하지 않지만 android logcat 에서 아래와 같은 에러가 발생합니다. reanimated, gesture handler 라이브러리 버전도 변경해봤지만 여전히 발생하고 있는데 도저히 원인이 뭔지 모르겠습니다. 또한 안드로이드, iOS 공통적으로 일정시간 동안 지도를 터치하거나 이동시 메모리가 환원되지 않고 memory leak 발생하여 앱 crash 발생하는 현상도 보이는데 아래 이슈와 관련된걸까요.
> 
> 확인 좀 부탁드려요. 감사합니다.
> 
> com.facebook.react.bridge.ReactNoCrashSoftException: Cannot find EventEmitter for receivedTouches: ReactTag[2131296476] UIManagerType[2] EventName[topTouchEnd] 12-20 08:52:07.599 25481 29106 E unknown:ReactEventEmitter: at com.facebook.react.uimanager.events.ReactEventEmitter.receiveTouches(ReactEventEmitter.java:74) 12-20 08:52:07.599 25481 29106 E unknown:ReactEventEmitter: at com.facebook.react.uimanager.events.TouchesHelper.sendTouchEvent(TouchesHelper.java:106) 12-20 08:52:07.599 25481 29106 E unknown:ReactEventEmitter: at com.facebook.react.uimanager.events.TouchEvent.dispatch(TouchEvent.java:166) 12-20 08:52:07.599 25481 29106 E unknown:ReactEventEmitter: at com.facebook.react.uimanager.events.TouchEvent.dispatchModern(TouchEvent.java:176) 12-20 08:52:07.599 25481 29106 E unknown:ReactEventEmitter: at com.facebook.react.uimanager.events.EventDispatcherImpl$DispatchEventsRunnable.run(EventDispatcherImpl.java:369) 12-20 08:52:07.599 25481 29106 E unknown:ReactEventEmitter: at android.os.Handler.handleCallback(Handler.java:883) 12-20 08:52:07.599 25481 29106 E unknown:ReactEventEmitter: at android.os.Handler.dispatchMessage(Handler.java:100) 12-20 08:52:07.599 25481 29106 E unknown:ReactEventEmitter: at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 12-20 08:52:07.599 25481 29106 E unknown:ReactEventEmitter: at android.os.Looper.loop(Looper.java:237) 12-20 08:52:07.599 25481 29106 E unknown:ReactEventEmitter: at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226) 12-20 08:52:07.599 25481 29106 E unknown:ReactEventEmitter: at java.lang.Thread.run(Thread.java:919) 12-20 08:52:07.748 782 855 E Netd : getNetworkForDns: getNetId from enterpriseCtrl is netid 0
> 
> ### Tested environment (Emulator? Real Device?)
> 안드로이드 실기기 공통적으로 발생.
> 
> ### Screen Shot

안녕하세요... 저도 동일한 문제를 경험하고 있는데, 혹시 해결 되셨을까요?
