### ISSUE TITLE
지도 클릭 시 앱 꺼짐

### ISSUE THREAD

**Issue by yhl0519** [QuadFlask/react-native-naver-map#97]
https://user-images.githubusercontent.com/62636978/119289086-e21a2000-bc84-11eb-9b36-71f2a8ae29ee.mp4

### Version of react-native-naver-map libraries

0.0.62

### Version of react-native

0.64.0

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

지도를 터치해서 이동하면 지도가 움직어야합니다.

### Actual behavior

ios 에서는 지도가 잘 이동이 되는데.
android 에서는 지도 클릭만해도 앱이 종료가됩니다.
에러도 안나요.

### Tested environment (Emulator? Real Device?)

Emulator, Device 둘다

**Comment by QuadFlask** [comment]
재현할 수 있는 샘플 프로젝트가 있을까요?
아마 안드로이드 로그캣에 로그가 있을것 같은데 혹시 확인해주실 수 있을까요?

**Comment by yhl0519** [comment]
> 재현 할 수있는 샘플 프로젝트가?
> 아마 안드로이드 로그 캣에 로그가 있을것 같은데 혹시 확인 해주실 수 있나요?

혹시 안드로이드 로그캣 어떻게 보는지 알 수 있을까요?

**Comment by yhl0519** [comment]
새로 프로젝트를 만들어 사용하니 새 프로젝트에서는 됩니다..
샘플 프로젝트를 드릴 순 없는데 혹시 예상되는 문제가 있을까요?
안드로이드 로그캣은 어떻게 보나요?

**Comment by QuadFlask** [comment]
adb logcat 명령어를 사용하시거나, 안드로이드 스튜디오에서 확인하실 수 있습니다.

**Comment by yhl0519** [comment]
혹시 네비게이션과 관련있는 문제가 있었던적이 있나요?

**Comment by yhl0519** [comment]
제가 지도 화면으로 넘어가기 전 화면에서 react-native-bit-swiper 라이브러리를 사용했는데
저거만 빼면 작동하고 넣으면 앱이 꺼집니다.. 
저 두가지로 문제가 있던적이 있습니까?

**Comment by yhl0519** [comment]
제 테스트코드 입니다. 


import React from 'react';
import {StyleSheet, View, Image} from 'react-native';
import NaverMapView, {Marker} from 'react-native-nmap';
import BitSwiper from 'react-native-bit-swiper';

const App = () => {
  const location = {
    latitude: 37.564362,
    longitude: 126.977011,
  };

  return (
    <>
      <NaverMapView
        style={styles.container}
        showsMyLocationButton={true}
        center={{...location, zoom: 16}}>
        <Marker coordinate={location} />
      </NaverMapView>
      <BitSwiper
        items={[
          'http://www.sisa-news.com/data/photos/20200936/art_159912317533_32480a.jpg',
          'https://newsimg.hankookilbo.com/cms/articlerelease/2020/09/13/c22a51dd-d1f8-48d2-82ad-f18a671078be.jpg',
        ]}
        itemWidth="80%" // 활성 아이템의 넓이
        inactiveItemScale={0.8} // 비활성 아이템의 스케일
        inactiveItemOpacity={0.5} // 비활성 아이템의 투명도
        inactiveItemOffset={30} // 비활성 아이템 표시 넓이
        onItemRender={(item, index) => (
          <View key={index} style={{height: 150}}>
            <Image
              source={{uri: item}}
              style={{width: '100%', height: '100%'}}
            />
          </View>
        )}
      />
    </>
  );
};

const styles = StyleSheet.create({
  container: {
    width: '100%',
    height: 300,
  },
});

export default App;

**Comment by QuadFlask** [comment]
https://github.com/facebook/react-native 31245 이슈와 관련이 있는것 같습니다. 0.65버전에서 수정될것 같네요. 0.63버전으로 내리거나 0.65버전을 기다려야할 것 같습니다. 

> 검색을 위해 로그를 올려둡니다
```
2021-05-24 17:16:11.257 6028-6110/com.awesomeproject D/SoLoader: Loaded: libnative-imagetranscoder.so
2021-05-24 17:16:14.128 6028-6028/com.awesomeproject E/InputEventReceiver: Exception dispatching input event.
2021-05-24 17:16:14.128 6028-6028/com.awesomeproject E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
2021-05-24 17:16:14.130 6028-6028/com.awesomeproject E/MessageQueue-JNI: java.lang.IllegalArgumentException: Unable to find JSIModule for class UIManager
        at com.facebook.react.bridge.JSIModuleRegistry.getModule(JSIModuleRegistry.java:24)
        at com.facebook.react.bridge.CatalystInstanceImpl.getJSIModule(CatalystInstanceImpl.java:564)
        at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:90)
        at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:46)
        at com.facebook.react.uimanager.UIManagerHelper.getUIManagerForReactTag(UIManagerHelper.java:40)
        at com.facebook.react.animated.NativeAnimatedNodesManager.handleEvent(NativeAnimatedNodesManager.java:505)
        at com.facebook.react.animated.NativeAnimatedNodesManager.onEventDispatch(NativeAnimatedNodesManager.java:483)
        at com.facebook.react.uimanager.events.EventDispatcherImpl.dispatchEvent(EventDispatcherImpl.java:116)
        at com.facebook.react.uimanager.JSTouchDispatcher.handleTouchEvent(JSTouchDispatcher.java:74)
        at com.facebook.react.ReactRootView.dispatchJSTouchEvent(ReactRootView.java:283)
        at com.facebook.react.ReactRootView.onInterceptTouchEvent(ReactRootView.java:201)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2573)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:440)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3400)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:398)
        at android.view.View.dispatchPointerEvent(View.java:12752)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5106)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4909)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4585)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4453)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4642)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4453)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7092)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7061)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7022)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7195)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
    	at java.lang.reflect.Method.invoke(Na
2021-05-24 17:16:14.131 6028-6028/com.awesomeproject D/AndroidRuntime: Shutting down VM


    --------- beginning of crash
2021-05-24 17:16:14.135 6028-6028/com.awesomeproject E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.awesomeproject, PID: 6028
    java.lang.IllegalArgumentException: Unable to find JSIModule for class UIManager
        at com.facebook.react.bridge.JSIModuleRegistry.getModule(JSIModuleRegistry.java:24)
        at com.facebook.react.bridge.CatalystInstanceImpl.getJSIModule(CatalystInstanceImpl.java:564)
        at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:90)
        at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:46)
        at com.facebook.react.uimanager.UIManagerHelper.getUIManagerForReactTag(UIManagerHelper.java:40)
        at com.facebook.react.animated.NativeAnimatedNodesManager.handleEvent(NativeAnimatedNodesManager.java:505)
        at com.facebook.react.animated.NativeAnimatedNodesManager.onEventDispatch(NativeAnimatedNodesManager.java:483)
        at com.facebook.react.uimanager.events.EventDispatcherImpl.dispatchEvent(EventDispatcherImpl.java:116)
        at com.facebook.react.uimanager.JSTouchDispatcher.handleTouchEvent(JSTouchDispatcher.java:74)
        at com.facebook.react.ReactRootView.dispatchJSTouchEvent(ReactRootView.java:283)
        at com.facebook.react.ReactRootView.onInterceptTouchEvent(ReactRootView.java:201)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2573)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:440)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3400)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:398)
        at android.view.View.dispatchPointerEvent(View.java:12752)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5106)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4909)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4585)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4453)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4642)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4453)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7092)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7061)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7022)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7195)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
2021-05-24 17:16:14.135 6028-6028/com.awesomeproject E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)


    --------- beginning of system
```

**Comment by yhl0519** [comment]
> https://github.com/facebook/react-native 31245 이슈와 관련이있는 것입니다. 0.65 버전에서 수정 될것 같네요. 0.63 버전으로 내리거나 0.65 버전을 기다려야 할 것입니다.
> 
> > 검색을 위해 올려 올려 둡니다
> 
> ```
> 2021-05-24 17:16:11.257 6028-6110/com.awesomeproject D/SoLoader: Loaded: libnative-imagetranscoder.so
> 2021-05-24 17:16:14.128 6028-6028/com.awesomeproject E/InputEventReceiver: Exception dispatching input event.
> 2021-05-24 17:16:14.128 6028-6028/com.awesomeproject E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
> 2021-05-24 17:16:14.130 6028-6028/com.awesomeproject E/MessageQueue-JNI: java.lang.IllegalArgumentException: Unable to find JSIModule for class UIManager
>         at com.facebook.react.bridge.JSIModuleRegistry.getModule(JSIModuleRegistry.java:24)
>         at com.facebook.react.bridge.CatalystInstanceImpl.getJSIModule(CatalystInstanceImpl.java:564)
>         at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:90)
>         at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:46)
>         at com.facebook.react.uimanager.UIManagerHelper.getUIManagerForReactTag(UIManagerHelper.java:40)
>         at com.facebook.react.animated.NativeAnimatedNodesManager.handleEvent(NativeAnimatedNodesManager.java:505)
>         at com.facebook.react.animated.NativeAnimatedNodesManager.onEventDispatch(NativeAnimatedNodesManager.java:483)
>         at com.facebook.react.uimanager.events.EventDispatcherImpl.dispatchEvent(EventDispatcherImpl.java:116)
>         at com.facebook.react.uimanager.JSTouchDispatcher.handleTouchEvent(JSTouchDispatcher.java:74)
>         at com.facebook.react.ReactRootView.dispatchJSTouchEvent(ReactRootView.java:283)
>         at com.facebook.react.ReactRootView.onInterceptTouchEvent(ReactRootView.java:201)
>         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2573)
>         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
>         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
>         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
>         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
>         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
>         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
>         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
>         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
>         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
>         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
>         at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:440)
>         at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
>         at android.app.Activity.dispatchTouchEvent(Activity.java:3400)
>         at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
>         at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:398)
>         at android.view.View.dispatchPointerEvent(View.java:12752)
>         at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5106)
>         at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4909)
>         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
>         at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
>         at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
>         at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4585)
>         at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4453)
>         at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4642)
>         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
>         at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
>         at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
>         at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4453)
>         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
>         at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7092)
>         at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7061)
>         at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7022)
>         at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7195)
>         at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
>         at android.os.MessageQueue.nativePollOnce(Native Method)
>         at android.os.MessageQueue.next(MessageQueue.java:326)
>         at android.os.Looper.loop(Looper.java:160)
>         at android.app.ActivityThread.main(ActivityThread.java:6669)
>     	at java.lang.reflect.Method.invoke(Na
> 2021-05-24 17:16:14.131 6028-6028/com.awesomeproject D/AndroidRuntime: Shutting down VM
> 
> 
>     --------- beginning of crash
> 2021-05-24 17:16:14.135 6028-6028/com.awesomeproject E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.awesomeproject, PID: 6028
>     java.lang.IllegalArgumentException: Unable to find JSIModule for class UIManager
>         at com.facebook.react.bridge.JSIModuleRegistry.getModule(JSIModuleRegistry.java:24)
>         at com.facebook.react.bridge.CatalystInstanceImpl.getJSIModule(CatalystInstanceImpl.java:564)
>         at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:90)
>         at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:46)
>         at com.facebook.react.uimanager.UIManagerHelper.getUIManagerForReactTag(UIManagerHelper.java:40)
>         at com.facebook.react.animated.NativeAnimatedNodesManager.handleEvent(NativeAnimatedNodesManager.java:505)
>         at com.facebook.react.animated.NativeAnimatedNodesManager.onEventDispatch(NativeAnimatedNodesManager.java:483)
>         at com.facebook.react.uimanager.events.EventDispatcherImpl.dispatchEvent(EventDispatcherImpl.java:116)
>         at com.facebook.react.uimanager.JSTouchDispatcher.handleTouchEvent(JSTouchDispatcher.java:74)
>         at com.facebook.react.ReactRootView.dispatchJSTouchEvent(ReactRootView.java:283)
>         at com.facebook.react.ReactRootView.onInterceptTouchEvent(ReactRootView.java:201)
>         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2573)
>         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
>         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
>         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
>         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
>         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
>         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
>         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
>         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
>         at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
>         at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
>         at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:440)
>         at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
>         at android.app.Activity.dispatchTouchEvent(Activity.java:3400)
>         at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
>         at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:398)
>         at android.view.View.dispatchPointerEvent(View.java:12752)
>         at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5106)
>         at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4909)
>         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
>         at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
>         at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
>         at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4585)
>         at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4453)
>         at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4642)
>         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
>         at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
>         at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
>         at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4453)
>         at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
>         at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7092)
>         at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7061)
>         at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7022)
>         at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7195)
>         at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
>         at android.os.MessageQueue.nativePollOnce(Native Method)
>         at android.os.MessageQueue.next(MessageQueue.java:326)
>         at android.os.Looper.loop(Looper.java:160)
> 2021-05-24 17:16:14.135 6028-6028/com.awesomeproject E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:6669)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
> 
> 
>     --------- beginning of system
> ```

감사합니다!! 0.63.4 로 낮추고 해결됐습니다 ㅎㅎ
